name: Panel Build and Deploy

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install & Build
        run: |
          npm ci --prefer-offline    # کمی سریع‌تر و پایدارتر از npm install
          npx vite build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: final-build

      - name: Copy to Server
        uses: appleboy/scp-action@v0.1.7   # نسخه جدیدتر
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: 2222
          timeout: 60s           # افزایش timeout اتصال
          command_timeout: 15m   # برای کپی فایل
          debug: true
          source: "final-build/*"
          target: "/var/www/admin-panel"
          strip_components: 1
          overwrite: true

      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 5m
          debug: true
          script: |
            docker exec moramor-nginx nginx -s reload || echo "Nginx reload failed"